// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260326002731-c322d1a39424 DO NOT EDIT.
package api

import (
	"github.com/labstack/echo/v5"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// AuthSpotifyResponse Response containing the access token
type AuthSpotifyResponse struct {
	// AccessToken The access token for the my.fm user.
	AccessToken string `json:"accessToken"`
}

// FormError Invalid form data
type FormError struct {
	Errors map[string]string `json:"errors"`
}

// GeneralError A general API error
type GeneralError struct {
	Error string `json:"error"`
}

// InternalServerError A general API error
type InternalServerError = GeneralError

// UnauthorizedError A general API error
type UnauthorizedError = GeneralError

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// Email The email of the user as per the auth provider.
	Email string `json:"email"`

	// Id The ID of the user.
	Id string `json:"id"`

	// Name The name of the user.
	Name string `json:"name"`

	// Onboarded Whether the user has finished being onboarded.
	Onboarded bool `json:"onboarded"`

	// Username The username of the user.
	Username string `json:"username"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// AuthSpotifyJSONBody defines parameters for AuthSpotify.
type AuthSpotifyJSONBody struct {
	// Code Authorization code from spotify.
	Code string `json:"code"`
}

// UsersOnboardJSONBody defines parameters for UsersOnboard.
type UsersOnboardJSONBody struct {
	// Name The user's display name (1-50 characters).
	Name string `json:"name"`

	// Username The user's username (2-30 characters, alphanumeric/underscore/hyphen only).
	Username string `json:"username"`
}

// AuthSpotifyJSONRequestBody defines body for AuthSpotify for application/json ContentType.
type AuthSpotifyJSONRequestBody AuthSpotifyJSONBody

// UsersOnboardJSONRequestBody defines body for UsersOnboard for application/json ContentType.
type UsersOnboardJSONRequestBody UsersOnboardJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate with Spotify
	// (POST /auth/spotify)
	AuthSpotify(ctx *echo.Context) error
	// Get the user's info.
	// (GET /user)
	User(ctx *echo.Context) error
	// Complete user onboarding.
	// (POST /users/onboard)
	UsersOnboard(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// AuthSpotify converts echo context to params.
func (w *ServerInterfaceWrapper) AuthSpotify(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AuthSpotify(ctx)
	return err
}

// User converts echo context to params.
func (w *ServerInterfaceWrapper) User(ctx *echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.User(ctx)
	return err
}

// UsersOnboard converts echo context to params.
func (w *ServerInterfaceWrapper) UsersOnboard(ctx *echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UsersOnboard(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/auth/spotify", wrapper.AuthSpotify)
	router.GET(baseURL+"/user", wrapper.User)
	router.POST(baseURL+"/users/onboard", wrapper.UsersOnboard)

}
