// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Scrobble struct {
	ID         string
	UserID     string
	CreatedAt  string
	SpotifyUri string
}

type User struct {
	ID                     string
	Username               string
	Name                   string
	Email                  string
	SpotifyAccessToken     sql.NullString
	SpotifyRefreshToken    sql.NullString
	SpotifyTokenExpiration sql.NullInt64
	CreatedAt              string
	Onboarded              sql.NullInt64
}
