// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, username, name, email, onboarded
) VALUES (
  ?, ?, ?, ?, FALSE
)
RETURNING id, username, name, email, spotify_access_token, spotify_refresh_token, spotify_token_expiration, created_at, onboarded
`

type CreateUserParams struct {
	ID       string
	Username string
	Name     string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.SpotifyAccessToken,
		&i.SpotifyRefreshToken,
		&i.SpotifyTokenExpiration,
		&i.CreatedAt,
		&i.Onboarded,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, name, email, spotify_access_token, spotify_refresh_token, spotify_token_expiration, created_at, onboarded FROM users
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.SpotifyAccessToken,
		&i.SpotifyRefreshToken,
		&i.SpotifyTokenExpiration,
		&i.CreatedAt,
		&i.Onboarded,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, name, email, spotify_access_token, spotify_refresh_token, spotify_token_expiration, created_at, onboarded FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.SpotifyAccessToken,
		&i.SpotifyRefreshToken,
		&i.SpotifyTokenExpiration,
		&i.CreatedAt,
		&i.Onboarded,
	)
	return i, err
}

const onboardUser = `-- name: OnboardUser :exec
UPDATE users
set username = ?,
    name = ?,
    onboarded = true
WHERE id = ?
`

type OnboardUserParams struct {
	Username string
	Name     string
	ID       string
}

func (q *Queries) OnboardUser(ctx context.Context, arg OnboardUserParams) error {
	_, err := q.db.ExecContext(ctx, onboardUser, arg.Username, arg.Name, arg.ID)
	return err
}

const updateUserSpotifyTokens = `-- name: UpdateUserSpotifyTokens :exec
UPDATE users
set spotify_access_token = ?,
    spotify_refresh_token = ?,
    spotify_token_expiration = ?
WHERE id = ?
`

type UpdateUserSpotifyTokensParams struct {
	SpotifyAccessToken     sql.NullString
	SpotifyRefreshToken    sql.NullString
	SpotifyTokenExpiration sql.NullInt64
	ID                     string
}

func (q *Queries) UpdateUserSpotifyTokens(ctx context.Context, arg UpdateUserSpotifyTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSpotifyTokens,
		arg.SpotifyAccessToken,
		arg.SpotifyRefreshToken,
		arg.SpotifyTokenExpiration,
		arg.ID,
	)
	return err
}
