// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { authSpotify, type Options, usersMe, usersOnboard } from '../sdk.gen';
import type { AuthSpotifyData, AuthSpotifyError, AuthSpotifyResponse2, UsersMeData, UsersMeError, UsersMeResponse, UsersOnboardData, UsersOnboardError, UsersOnboardResponse } from '../types.gen';

/**
 * Authenticate with Spotify
 *
 * Exchanges Spotify authorization code for my.fm access token. If no my.fm account exists with the associated Spotify email, one is created.
 *
 */
export const authSpotifyMutation = (options?: Partial<Options<AuthSpotifyData>>): UseMutationOptions<AuthSpotifyResponse2, AuthSpotifyError, Options<AuthSpotifyData>> => {
    const mutationOptions: UseMutationOptions<AuthSpotifyResponse2, AuthSpotifyError, Options<AuthSpotifyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authSpotify({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const usersMeQueryKey = (options?: Options<UsersMeData>) => createQueryKey('usersMe', options);

/**
 * Get user info.
 *
 * Returns information about the currently authenticated user.
 *
 */
export const usersMeOptions = (options?: Options<UsersMeData>) => queryOptions<UsersMeResponse, UsersMeError, UsersMeResponse, ReturnType<typeof usersMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await usersMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersMeQueryKey(options)
});

/**
 * Complete user onboarding.
 *
 * Sets the user's name and username, marking them as onboarded. Cannot be called if the user is already onboarded.
 *
 */
export const usersOnboardMutation = (options?: Partial<Options<UsersOnboardData>>): UseMutationOptions<UsersOnboardResponse, UsersOnboardError, Options<UsersOnboardData>> => {
    const mutationOptions: UseMutationOptions<UsersOnboardResponse, UsersOnboardError, Options<UsersOnboardData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersOnboard({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
