// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getUser, getUsers, type Options, postAuthSpotify, putUserProfile } from '../sdk.gen';
import type { GetUserData, GetUserError, GetUserResponse, GetUsersData, GetUsersError, GetUsersResponse, PostAuthSpotifyData, PostAuthSpotifyError, PostAuthSpotifyResponse, PutUserProfileData, PutUserProfileError, PutUserProfileResponse } from '../types.gen';

/**
 * Authenticate with Spotify
 *
 * Exchanges Spotify authorization code for my.fm access token. If no my.fm account exists with the associated Spotify email, one is created.
 *
 */
export const postAuthSpotifyMutation = (options?: Partial<Options<PostAuthSpotifyData>>): UseMutationOptions<PostAuthSpotifyResponse, PostAuthSpotifyError, Options<PostAuthSpotifyData>> => {
    const mutationOptions: UseMutationOptions<PostAuthSpotifyResponse, PostAuthSpotifyError, Options<PostAuthSpotifyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthSpotify({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getUserQueryKey = (options?: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * Get the user's info.
 *
 * Returns information about the currently authenticated user.
 *
 */
export const getUserOptions = (options?: Options<GetUserData>) => queryOptions<GetUserResponse, GetUserError, GetUserResponse, ReturnType<typeof getUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserQueryKey(options)
});

/**
 * Complete user onboarding.
 *
 * Sets the user's name and username, marking them as onboarded. Can only be called once (cannot be called if the user is onboarded.)
 *
 */
export const putUserProfileMutation = (options?: Partial<Options<PutUserProfileData>>): UseMutationOptions<PutUserProfileResponse, PutUserProfileError, Options<PutUserProfileData>> => {
    const mutationOptions: UseMutationOptions<PutUserProfileResponse, PutUserProfileError, Options<PutUserProfileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putUserProfile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUsersQueryKey = (options: Options<GetUsersData>) => createQueryKey('getUsers', options);

/**
 * Get a user's public profile.
 *
 * Returns some public information about a given user.
 *
 */
export const getUsersOptions = (options: Options<GetUsersData>) => queryOptions<GetUsersResponse, GetUsersError, GetUsersResponse, ReturnType<typeof getUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersQueryKey(options)
});
