// This file is auto-generated by @hey-api/openapi-ts

export { authSpotify, type Options, usersMe, usersOnboard } from './sdk.gen';
export type { AuthSpotifyData, AuthSpotifyError, AuthSpotifyErrors, AuthSpotifyResponse, AuthSpotifyResponse2, AuthSpotifyResponses, ClientOptions, FormError, GeneralError, UsersMeData, UsersMeError, UsersMeErrors, UsersMeResponse, UsersMeResponses, UsersOnboardData, UsersOnboardError, UsersOnboardErrors, UsersOnboardResponse, UsersOnboardResponses } from './types.gen';
