// This file is auto-generated by @hey-api/openapi-ts

export { authSpotify, type Options, user, usersOnboard } from './sdk.gen';
export type { AuthSpotifyData, AuthSpotifyError, AuthSpotifyErrors, AuthSpotifyResponse, AuthSpotifyResponse2, AuthSpotifyResponses, ClientOptions, FormError, GeneralError, UserData, UserError, UserErrors, UserResponse, UserResponses, UsersOnboardData, UsersOnboardError, UsersOnboardErrors, UsersOnboardResponse, UsersOnboardResponses } from './types.gen';
