// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AuthSpotifyData,
  AuthSpotifyErrors,
  AuthSpotifyResponses,
  UserMeData,
  UserMeErrors,
  UserMeResponses,
  UserOnboardData,
  UserOnboardErrors,
  UserOnboardResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Authenticate with Spotify
 *
 * Exchanges Spotify authorization code for my.fm access token. If no my.fm account exists with the associated Spotify email, one is created.
 *
 */
export const authSpotify = <ThrowOnError extends boolean = false>(
  options: Options<AuthSpotifyData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthSpotifyResponses, AuthSpotifyErrors, ThrowOnError>({
    url: "/auth/spotify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get user info.
 *
 * Returns information about the currently authenticated user.
 *
 */
export const userMe = <ThrowOnError extends boolean = false>(
  options?: Options<UserMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<UserMeResponses, UserMeErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/user/me",
    ...options,
  });

/**
 * Complete user onboarding.
 *
 * Sets the user's name and username, marking them as onboarded. Cannot be called if the user is already onboarded.
 *
 */
export const userOnboard = <ThrowOnError extends boolean = false>(
  options: Options<UserOnboardData, ThrowOnError>,
) =>
  (options.client ?? client).post<UserOnboardResponses, UserOnboardErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/user/onboard",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
