// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.my.fm" | (string & {});
};

/**
 * Response containing the access token
 */
export type AuthSpotifyResponse = {
  /**
   * The access token for the my.fm user.
   */
  accessToken: string;
};

/**
 * A general API error
 */
export type GeneralError = {
  error: string;
};

/**
 * Invalid form data
 */
export type FormError = {
  errors: {
    [key: string]: string;
  };
};

export type AuthSpotifyData = {
  body: {
    /**
     * Authorization code from spotify.
     */
    code: string;
  };
  path?: never;
  query?: never;
  url: "/auth/spotify";
};

export type AuthSpotifyErrors = {
  /**
   * Invalid authorization code.
   */
  400: GeneralError;
  /**
   * Unexpected internal error.
   */
  500: GeneralError;
};

export type AuthSpotifyError = AuthSpotifyErrors[keyof AuthSpotifyErrors];

export type AuthSpotifyResponses = {
  /**
   * An access token for the user.
   */
  200: AuthSpotifyResponse;
};

export type AuthSpotifyResponse2 = AuthSpotifyResponses[keyof AuthSpotifyResponses];

export type UserMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/user/me";
};

export type UserMeErrors = {
  /**
   * User is unauthorized.
   */
  401: GeneralError;
  /**
   * Unexpected internal error.
   */
  500: GeneralError;
};

export type UserMeError = UserMeErrors[keyof UserMeErrors];

export type UserMeResponses = {
  /**
   * Information about a user.
   */
  200: {
    /**
     * The ID of the user.
     */
    id: string;
    /**
     * The email of the user as per the auth provider.
     */
    email: string;
    /**
     * The name of the user.
     */
    name: string;
    /**
     * The username of the user.
     */
    username: string;
    /**
     * Whether the user has finished being onboarded.
     */
    onboarded: boolean;
  };
};

export type UserMeResponse = UserMeResponses[keyof UserMeResponses];

export type UserOnboardingData = {
  body: {
    /**
     * The user's display name (1-50 characters).
     */
    name: string;
    /**
     * The user's username (2-30 characters, alphanumeric/underscore/hyphen only).
     */
    username: string;
  };
  path?: never;
  query?: never;
  url: "/user/onboarding";
};

export type UserOnboardingErrors = {
  /**
   * Invalid request data. This can be due to: - User is already onboarded - Name is not between 1-50 characters - Username is not between 2-30 characters - Username contains invalid characters (only letters, numbers, underscores, and hyphens allowed)
   *
   */
  400: FormError | GeneralError;
  /**
   * User is unauthorized.
   */
  401: GeneralError;
  /**
   * Unexpected internal error.
   */
  500: GeneralError;
};

export type UserOnboardingError = UserOnboardingErrors[keyof UserOnboardingErrors];

export type UserOnboardingResponses = {
  /**
   * Onboarding completed successfully.
   */
  204: void;
};

export type UserOnboardingResponse = UserOnboardingResponses[keyof UserOnboardingResponses];
